# Generated by Django 3.0 on 2020-04-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('pdf_location', models.CharField(default='', max_length=200)),
                ('thumbnail', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
