# Generated by Django 3.0 on 2020-04-27 11:58

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_shells'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_book',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d', validators=[books.models.validate_file_extension]),
        ),
    ]
