# Generated by Django 3.0 on 2020-04-27 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_file_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='shell',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.shells'),
        ),
    ]
