# Generated by Django 3.0 on 2020-04-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200427_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_location',
        ),
    ]
