# Generated by Django 3.0 on 2020-04-28 09:30

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_pdf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='documents/%Y/%m%d', validators=[books.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_book',
            field=models.FileField(default='', upload_to='documents/%Y/%m%d', validators=[books.models.validate_file_extension]),
        ),
    ]
