# Generated by Django 3.0 on 2020-05-10 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200428_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
