# Generated by Django 3.0 on 2020-05-20 06:58

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_book',
            field=models.FileField(default='', unique=True, upload_to='documents/%Y/%m%d', validators=[books.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='shells',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
