# Generated by Django 3.0.1 on 2020-06-12 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_reader_mobile'),
        ('books', '0011_book_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='reading_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_read_page', models.IntegerField()),
                ('last_reading_date', models.DateField(auto_now_add=True)),
                ('last_reading_time', models.TimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader')),
            ],
            options={
                'unique_together': {('book', 'reader')},
            },
        ),
    ]
