# Generated by Django 3.0.1 on 2020-06-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_reader_mobile'),
        ('books', '0013_auto_20200612_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_record',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
        ),
    ]
