# Generated by Django 3.0.1 on 2020-06-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_reader_mobile'),
        ('books', '0015_reading_record_total_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='upload_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
        ),
    ]
