# Generated by Django 3.0.1 on 2020-06-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_reader_mobile'),
        ('books', '0016_auto_20200613_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='shells',
            name='contrib',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shells',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shells',
            name='upload_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reader.reader'),
        ),
    ]
