# Generated by Django 3.0.7 on 2020-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20200613_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='shells',
            name='create_on',
            field=models.DateField(auto_now_add=True, default='01-01-2000'),
            preserve_default=False,
        ),
    ]
