# Generated by Django 3.0.7 on 2020-06-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_shells_create_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shells',
            name='create_on',
        ),
    ]
