# Generated by Django 3.0.7 on 2020-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_remove_shells_create_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='shells',
            name='create_on',
            field=models.DateField(auto_now_add=True, default='2020-05-07'),
            preserve_default=False,
        ),
    ]
