# Generated by Django 3.0.1 on 2020-06-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='mobile',
        ),
    ]
